#!/usr/bin/env python3
"""Benchmark the specialist tools against ground-truth labels in samples/.

  * Change detection  vs LEVIR-CD change masks          -> precision / recall / F1 / IoU
  * Water mapping     vs Sen1Floods11 hand labels (India) -> IoU for optical, SAR and fused maps
                                                           (only if those chips were downloaded)

Writes docs/benchmarks.md and prints a summary. Run after scripts/fetch_samples.py:
    python scripts/evaluate.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.raster import load_scene  # noqa: E402
from app.tools.change import detect_change  # noqa: E402
from app.tools.fusion import fuse  # noqa: E402
from app.tools.landcover import classify  # noqa: E402
from app.tools.sar import sar_water  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SAMPLES = ROOT / "samples"


def scores(pred: np.ndarray, gt: np.ndarray, valid: np.ndarray | None = None) -> dict:
    if valid is not None:
        pred, gt = pred[valid], gt[valid]
    tp = int((pred & gt).sum())
    fp = int((pred & ~gt).sum())
    fn = int((~pred & gt).sum())
    p = tp / (tp + fp) if tp + fp else 0.0
    r = tp / (tp + fn) if tp + fn else 0.0
    return {"tp": tp, "fp": fp, "fn": fn, "precision": p, "recall": r,
            "f1": 2 * p * r / (p + r) if p + r else 0.0, "iou": tp / (tp + fp + fn) if tp + fp + fn else 1.0}


def pooled(rows: list[dict]) -> dict:
    tp, fp, fn = (sum(r[k] for r in rows) for k in ("tp", "fp", "fn"))
    p, r = tp / max(tp + fp, 1), tp / max(tp + fn, 1)
    return {"precision": p, "recall": r, "f1": 2 * p * r / max(p + r, 1e-9), "iou": tp / max(tp + fp + fn, 1)}


def main():
    cat = json.loads((SAMPLES / "catalog.json").read_text())
    lines = ["# Benchmarks", "",
             f"Generated by `backend/scripts/evaluate.py` on {time.strftime('%Y-%m-%d')}. "
             "All numbers are computed on CPU against the ground-truth labels shipped with each dataset. "
             "Pooled scores sum TP/FP/FN over all pixels of all samples.", ""]

    # ---------------------------------------------------------------- change detection
    from app.ml import changeformer

    backends = ["classical"] + (["changeformer"] if changeformer.available() else [])
    levir = [it for it in cat if it["id"].startswith("levir") and "labels" in it]
    summary = {}
    for be in backends:
        rows, ms = [], []
        for it in levir:
            a = load_scene(SAMPLES / it["files"][0]["file"], gsd_m=0.5, modality="optical")
            b = load_scene(SAMPLES / it["files"][1]["file"], gsd_m=0.5, modality="optical")
            gt = np.array(Image.open(SAMPLES / it["labels"])) > 0
            detect_change(a, b, backend=be)  # warm-up (model load) excluded from timing
            t = time.perf_counter()
            pred = detect_change(a, b, backend=be)["mask"]
            ms.append((time.perf_counter() - t) * 1000)
            rows.append(scores(pred, gt) | {"id": it["id"]})
        summary[be] = (rows, pooled(rows), float(np.mean(ms)))
        print(f"Change detection [{be}] pooled F1={summary[be][1]['f1']:.3f} IoU={summary[be][1]['iou']:.3f}")
    if levir:
        names = {"classical": "Classical (histogram matching + CVA + SSIM, no training)",
                 "changeformer": "ChangeFormerV6, pretrained on LEVIR-CD train split (open weights, GitHub)"}
        lines += ["## Change detection — LEVIR-CD test samples", "",
                  f"{len(levir)} pairs from the LEVIR-CD **test** split (256×256 px, 0.5 m), which the pretrained "
                  "model never saw during training.", "",
                  "| Method | Precision | Recall | F1 | IoU | CPU time / pair |", "|---|---|---|---|---|---|"]
        for be, (_rows, pl, ms) in summary.items():
            lines.append(f"| {names[be]} | {pl['precision']:.3f} | {pl['recall']:.3f} | **{pl['f1']:.3f}** | "
                         f"{pl['iou']:.3f} | {ms:.0f} ms |")
        lines += ["", "Per-pair F1:", "", "| Pair | " + " | ".join(summary) + " |",
                  "|---|" + "---|" * len(summary)]
        for i, it in enumerate(levir):
            lines.append(f"| {it['id']} | " + " | ".join(f"{summary[be][0][i]['f1']:.3f}" for be in summary) + " |")
        lines += ["", "Five pairs is a small sample: treat these as a sanity check. The ChangeFormer paper reports "
                  "F1 = 0.904 on the full 2,048-tile LEVIR-CD test set. CPU time measured on a 2-core cloud VM; "
                  "a laptop is typically faster, a GPU much faster.", ""]

    # ---------------------------------------------------------------- water / fusion
    wrows = {"optical": [], "sar": [], "fused": []}
    for it in cat:
        if not it["id"].startswith("s1f-"):
            continue
        import rasterio

        with rasterio.open(SAMPLES / it["labels"]) as src:
            lab = src.read(1)
        valid, gt = lab >= 0, lab == 1
        opt = load_scene(SAMPLES / it["files"][0]["file"], modality="optical")
        sar = load_scene(SAMPLES / it["files"][1]["file"], modality="sar")
        if opt.shape != lab.shape:  # only if max_px downsampled; chips are 512 px so this should not trigger
            continue
        wrows["optical"].append(scores(classify(opt)["masks"]["water"], gt, valid))
        wrows["sar"].append(scores(sar_water(sar)["mask"], gt, valid))
        wrows["fused"].append(scores(fuse(opt, sar)["mask"], gt, valid))
    if wrows["fused"]:
        lines += ["## Water / flood mapping — Sen1Floods11 India chips", "",
                  f"{len(wrows['fused'])} hand-labelled 512×512 chips at 10 m. No training; thresholds are per-scene Otsu.", "",
                  "| Input | Precision | Recall | F1 | IoU |", "|---|---|---|---|---|"]
        for k in ("optical", "sar", "fused"):
            pl = pooled(wrows[k])
            lines.append(f"| {k} | {pl['precision']:.3f} | {pl['recall']:.3f} | {pl['f1']:.3f} | {pl['iou']:.3f} |")
            print(f"Water IoU {k}: {pl['iou']:.3f}")
        lines.append("")
    else:
        lines += ["## Water / flood mapping — Sen1Floods11", "",
                  "Not run: download the India chips with `python scripts/fetch_samples.py` (needs access to "
                  "storage.googleapis.com), then re-run this script.", ""]

    out = ROOT / "docs" / "benchmarks.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
