#!/usr/bin/env python3
"""Benchmark the specialist tools against ground-truth labels in samples/.

  * Change detection  vs LEVIR-CD change masks          -> precision / recall / F1 / IoU
  * Water mapping     vs Sen1Floods11 hand labels (India) -> IoU for optical, SAR and fused maps
                                                           (only if those chips were downloaded)

Writes docs/benchmarks.md and prints a summary. Run after scripts/fetch_samples.py:
    python scripts/evaluate.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.raster import load_scene  # noqa: E402
from app.tools.change import detect_change  # noqa: E402
from app.tools.fusion import fuse  # noqa: E402
from app.tools.landcover import classify  # noqa: E402
from app.tools.sar import sar_water  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SAMPLES = ROOT / "samples"


def scores(pred: np.ndarray, gt: np.ndarray, valid: np.ndarray | None = None) -> dict:
    if valid is not None:
        pred, gt = pred[valid], gt[valid]
    tp = int((pred & gt).sum())
    fp = int((pred & ~gt).sum())
    fn = int((~pred & gt).sum())
    p = tp / (tp + fp) if tp + fp else 0.0
    r = tp / (tp + fn) if tp + fn else 0.0
    return {"tp": tp, "fp": fp, "fn": fn, "precision": p, "recall": r,
            "f1": 2 * p * r / (p + r) if p + r else 0.0, "iou": tp / (tp + fp + fn) if tp + fp + fn else 1.0}


def pooled(rows: list[dict]) -> dict:
    tp, fp, fn = (sum(r[k] for r in rows) for k in ("tp", "fp", "fn"))
    p, r = tp / max(tp + fp, 1), tp / max(tp + fn, 1)
    return {"precision": p, "recall": r, "f1": 2 * p * r / max(p + r, 1e-9), "iou": tp / max(tp + fp + fn, 1)}


def main():
    cat = json.loads((SAMPLES / "catalog.json").read_text())
    lines = ["# Benchmarks", "",
             f"Generated by `backend/scripts/evaluate.py` on {time.strftime('%Y-%m-%d')}. "
             "All numbers are computed on CPU against the ground-truth labels shipped with each dataset. "
             "Pooled scores sum TP/FP/FN over all pixels of all samples.", ""]

    # ---------------------------------------------------------------- change detection
    cd_rows, cd_ms = [], []
    for it in cat:
        if not it["id"].startswith("levir") or "labels" not in it:
            continue
        a = load_scene(SAMPLES / it["files"][0]["file"], gsd_m=0.5, modality="optical")
        b = load_scene(SAMPLES / it["files"][1]["file"], gsd_m=0.5, modality="optical")
        gt = np.array(Image.open(SAMPLES / it["labels"])) > 0
        t = time.perf_counter()
        pred = detect_change(a, b)["mask"]
        cd_ms.append((time.perf_counter() - t) * 1000)
        cd_rows.append(scores(pred, gt) | {"id": it["id"]})
    if cd_rows:
        pl = pooled(cd_rows)
        lines += ["## Change detection — LEVIR-CD samples", "",
                  f"Method: unsupervised histogram matching + CVA + SSIM, Otsu threshold (no training). "
                  f"{len(cd_rows)} pairs, 256×256 px at 0.5 m.", "",
                  "| Pair | Precision | Recall | F1 | IoU |", "|---|---|---|---|---|"]
        lines += [f"| {r['id']} | {r['precision']:.3f} | {r['recall']:.3f} | {r['f1']:.3f} | {r['iou']:.3f} |" for r in cd_rows]
        lines += [f"| **pooled** | **{pl['precision']:.3f}** | **{pl['recall']:.3f}** | **{pl['f1']:.3f}** | **{pl['iou']:.3f}** |",
                  "", f"Mean latency: {np.mean(cd_ms):.0f} ms per pair on CPU.", "",
                  "For context, supervised deep models (BIT, ChangeFormer) report F1 ≈ 0.89–0.90 on the full "
                  "LEVIR-CD test set; plugging one in behind `detect_change()` is the planned GPU upgrade.", ""]
        print(f"Change detection pooled F1={pl['f1']:.3f} IoU={pl['iou']:.3f} over {len(cd_rows)} pairs")

    # ---------------------------------------------------------------- water / fusion
    wrows = {"optical": [], "sar": [], "fused": []}
    for it in cat:
        if not it["id"].startswith("s1f-"):
            continue
        import rasterio

        with rasterio.open(SAMPLES / it["labels"]) as src:
            lab = src.read(1)
        valid, gt = lab >= 0, lab == 1
        opt = load_scene(SAMPLES / it["files"][0]["file"], modality="optical")
        sar = load_scene(SAMPLES / it["files"][1]["file"], modality="sar")
        if opt.shape != lab.shape:  # only if max_px downsampled; chips are 512 px so this should not trigger
            continue
        wrows["optical"].append(scores(classify(opt)["masks"]["water"], gt, valid))
        wrows["sar"].append(scores(sar_water(sar)["mask"], gt, valid))
        wrows["fused"].append(scores(fuse(opt, sar)["mask"], gt, valid))
    if wrows["fused"]:
        lines += ["## Water / flood mapping — Sen1Floods11 India chips", "",
                  f"{len(wrows['fused'])} hand-labelled 512×512 chips at 10 m. No training; thresholds are per-scene Otsu.", "",
                  "| Input | Precision | Recall | F1 | IoU |", "|---|---|---|---|---|"]
        for k in ("optical", "sar", "fused"):
            pl = pooled(wrows[k])
            lines.append(f"| {k} | {pl['precision']:.3f} | {pl['recall']:.3f} | {pl['f1']:.3f} | {pl['iou']:.3f} |")
            print(f"Water IoU {k}: {pl['iou']:.3f}")
        lines.append("")
    else:
        lines += ["## Water / flood mapping — Sen1Floods11", "",
                  "Not run: download the India chips with `python scripts/fetch_samples.py` (needs access to "
                  "storage.googleapis.com), then re-run this script.", ""]

    out = ROOT / "docs" / "benchmarks.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
